// ============================================================
// 人脉升级配置 (AngelUpgradeDef) — 消耗人脉购买永久升级
// 对标 Adventure Capitalist 天使投资人升级系统
// 策略抉择：花费人脉→获得强力升级→但倍率降低→需更多轮次补偿
// ============================================================
import { AngelUpgradeDef } from '../types';

export const ANGEL_UPGRADES: AngelUpgradeDef[] = [
  // === 产线利润 ×3（10条产线各一个） ===
  {
    id: 1,
    name: '钢化膜秘方',
    description: '路边摊独家配方，利润提升至3倍',
    icon: '📜',
    cost: 1,
    effectType: 'profit_mult_business',
    effectValue: 3,
    targetBusinessId: 1,
  },
  {
    id: 2,
    name: '校园垄断协议',
    description: '签下校方独家经营权，利润提升至3倍',
    icon: '📋',
    cost: 3,
    effectType: 'profit_mult_business',
    effectValue: 3,
    targetBusinessId: 2,
  },
  {
    id: 3,
    name: '黄金铺位',
    description: '买下商场最佳位置，利润提升至3倍',
    icon: '🏗️',
    cost: 5,
    effectType: 'profit_mult_business',
    effectValue: 3,
    targetBusinessId: 3,
  },
  {
    id: 4,
    name: '加盟费全免',
    description: '零加盟费模式，利润提升至3倍',
    icon: '🎁',
    cost: 10,
    effectType: 'profit_mult_business',
    effectValue: 3,
    targetBusinessId: 4,
  },
  {
    id: 5,
    name: '算法推荐',
    description: '直播间算法全开推流，利润提升至3倍',
    icon: '🤖',
    cost: 25,
    effectType: 'profit_mult_business',
    effectValue: 3,
    targetBusinessId: 5,
  },
  {
    id: 6,
    name: '工业4.0改造',
    description: '智能化产线全面升级，利润提升至3倍',
    icon: '🔧',
    cost: 50,
    effectType: 'profit_mult_business',
    effectValue: 3,
    targetBusinessId: 6,
  },
  {
    id: 7,
    name: '诺贝尔加持',
    description: '诺贝尔奖光环加持，利润提升至3倍',
    icon: '🏅',
    cost: 100,
    effectType: 'profit_mult_business',
    effectValue: 3,
    targetBusinessId: 7,
  },
  {
    id: 8,
    name: '朋友圈升级',
    description: 'LVMH/爱马仕CEO直连，利润提升至3倍',
    icon: '📱',
    cost: 200,
    effectType: 'profit_mult_business',
    effectValue: 3,
    targetBusinessId: 8,
  },
  {
    id: 9,
    name: '免税通道',
    description: '全球免税贸易协定，利润提升至3倍',
    icon: '🛃',
    cost: 500,
    effectType: 'profit_mult_business',
    effectValue: 3,
    targetBusinessId: 9,
  },
  {
    id: 10,
    name: '宇宙垄断法案',
    description: '全宇宙唯一的屏保供应商，利润提升至3倍',
    icon: '🌍',
    cost: 1000,
    effectType: 'profit_mult_business',
    effectValue: 3,
    targetBusinessId: 10,
  },

  // === 全局加成升级 ===
  {
    id: 101,
    name: '膜界至尊',
    description: '全产线利润×3，真正的膜界霸主',
    icon: '👑',
    cost: 300,
    effectType: 'profit_mult_all',
    effectValue: 3,
  },
  {
    id: 102,
    name: '膜界神话',
    description: '全产线利润再×3，传说中的不败传奇',
    icon: '🏆',
    cost: 2000,
    effectType: 'profit_mult_all',
    effectValue: 3,
  },
  {
    id: 103,
    name: '批发进货',
    description: '全产线购买成本降低25%',
    icon: '📦',
    cost: 50,
    effectType: 'cost_reduce_all',
    effectValue: 0.25,
  },
  {
    id: 104,
    name: '源头直供',
    description: '跳过所有中间商，购买成本再降25%',
    icon: '🏭',
    cost: 200,
    effectType: 'cost_reduce_all',
    effectValue: 0.25,
  },
  {
    id: 105,
    name: '闪电生产',
    description: '全产线生产速度提升30%',
    icon: '⚡',
    cost: 100,
    effectType: 'cycle_reduce_all',
    effectValue: 0.30,
  },
  {
    id: 106,
    name: '极速产线',
    description: '全产线生产速度再提升30%',
    icon: '🚀',
    cost: 400,
    effectType: 'cycle_reduce_all',
    effectValue: 0.30,
  },
];
