// ============================================================
// 产线专属升级配置 (BusinessUpgradeDef)
// 对标 Adventure Capitalist 每条产线的现金升级系统
// 每条产线3个升级：×2利润、×3利润、−25%周期
// 用当前现金购买，一次性永久效果
// ============================================================
import { BusinessUpgradeDef } from '../types';

export const BUSINESS_UPGRADES: BusinessUpgradeDef[] = [
  // === 产线1: 路边钢化膜摊 ===
  {
    id: 101,
    businessId: 1,
    name: '优质膜材',
    description: '进口日本材料，单次利润翻倍',
    icon: '💎',
    cost: 400,
    effectType: 'profit_mult',
    effectValue: 2,
    unlockQuantity: 25,
  },
  {
    id: 102,
    businessId: 1,
    name: 'VIP客户群',
    description: '积累高端客户，利润再×3',
    icon: '👑',
    cost: 4000,
    effectType: 'profit_mult',
    effectValue: 3,
    unlockQuantity: 50,
  },
  {
    id: 103,
    businessId: 1,
    name: '流水线贴膜',
    description: '标准化操作流程，生产速度提升25%',
    icon: '⚡',
    cost: 40000,
    effectType: 'cycle_reduce',
    effectValue: 0.25,
    unlockQuantity: 100,
  },

  // === 产线2: 校园快贴车 ===
  {
    id: 201,
    businessId: 2,
    name: '学生会合作',
    description: '官方合作渠道，单次利润翻倍',
    icon: '🎓',
    cost: 6000,
    effectType: 'profit_mult',
    effectValue: 2,
    unlockQuantity: 25,
  },
  {
    id: 202,
    businessId: 2,
    name: '校园垄断',
    description: '独家经营权覆盖全校，利润×3',
    icon: '🏫',
    cost: 60000,
    effectType: 'profit_mult',
    effectValue: 3,
    unlockQuantity: 50,
  },
  {
    id: 203,
    businessId: 2,
    name: '社团分润',
    description: '社团帮你推广，生产速度+25%',
    icon: '⚡',
    cost: 600000,
    effectType: 'cycle_reduce',
    effectValue: 0.25,
    unlockQuantity: 100,
  },

  // === 产线3: 商场贴膜亭 ===
  {
    id: 301,
    businessId: 3,
    name: '黄金位置',
    description: '商场入口C位，利润翻倍',
    icon: '🏬',
    cost: 72000,
    effectType: 'profit_mult',
    effectValue: 2,
    unlockQuantity: 25,
  },
  {
    id: 302,
    businessId: 3,
    name: '品牌联营',
    description: '与手机品牌联名，利润×3',
    icon: '🤝',
    cost: 720000,
    effectType: 'profit_mult',
    effectValue: 3,
    unlockQuantity: 50,
  },
  {
    id: 303,
    businessId: 3,
    name: 'VIP预约制',
    description: '预约系统减少等待，生产速度+25%',
    icon: '⚡',
    cost: 7200000,
    effectType: 'cycle_reduce',
    effectValue: 0.25,
    unlockQuantity: 100,
  },

  // === 产线4: 连锁门店 ===
  {
    id: 401,
    businessId: 4,
    name: '标准化手册',
    description: '统一SOP操作手册，利润翻倍',
    icon: '📋',
    cost: 864000,
    effectType: 'profit_mult',
    effectValue: 2,
    unlockQuantity: 25,
  },
  {
    id: 402,
    businessId: 4,
    name: '区域保护',
    description: '独占区域经营权，利润×3',
    icon: '🗺️',
    cost: 8640000,
    effectType: 'profit_mult',
    effectValue: 3,
    unlockQuantity: 50,
  },
  {
    id: 403,
    businessId: 4,
    name: '自动化门店',
    description: '无人化运营系统，速度+25%',
    icon: '🤖',
    cost: 86400000,
    effectType: 'cycle_reduce',
    effectValue: 0.25,
    unlockQuantity: 100,
  },

  // === 产线5: 直播电商间 ===
  {
    id: 501,
    businessId: 5,
    name: '算法优化',
    description: '买通推荐算法，流量翻倍利润翻倍',
    icon: '📱',
    cost: 10368000,
    effectType: 'profit_mult',
    effectValue: 2,
    unlockQuantity: 25,
  },
  {
    id: 502,
    businessId: 5,
    name: '头部主播',
    description: '签约千万粉丝主播，利润×3',
    icon: '🎤',
    cost: 103680000,
    effectType: 'profit_mult',
    effectValue: 3,
    unlockQuantity: 50,
  },
  {
    id: 503,
    businessId: 5,
    name: '自动发货',
    description: '智能仓储自动发货，速度+25%',
    icon: '📦',
    cost: 1036800000,
    effectType: 'cycle_reduce',
    effectValue: 0.25,
    unlockQuantity: 100,
  },

  // === 产线6: OEM代工厂 ===
  {
    id: 601,
    businessId: 6,
    name: '专利技术',
    description: '自研核心专利，利润翻倍',
    icon: '🔬',
    cost: 124416000,
    effectType: 'profit_mult',
    effectValue: 2,
    unlockQuantity: 25,
  },
  {
    id: 602,
    businessId: 6,
    name: '规模效应',
    description: '量产摊薄成本，利润×3',
    icon: '🏭',
    cost: 1244160000,
    effectType: 'profit_mult',
    effectValue: 3,
    unlockQuantity: 50,
  },
  {
    id: 603,
    businessId: 6,
    name: '机器人产线',
    description: '全机器人生产，速度+25%',
    icon: '🦾',
    cost: 12441600000,
    effectType: 'cycle_reduce',
    effectValue: 0.25,
    unlockQuantity: 100,
  },

  // === 产线7: 纳米膜研发中心 ===
  {
    id: 701,
    businessId: 7,
    name: '实验室扩建',
    description: '新建三个实验室，利润翻倍',
    icon: '🧪',
    cost: 1492992000,
    effectType: 'profit_mult',
    effectValue: 2,
    unlockQuantity: 25,
  },
  {
    id: 702,
    businessId: 7,
    name: '诺贝尔团队',
    description: '挖来诺贝尔奖得主，利润×3',
    icon: '🏅',
    cost: 14929920000,
    effectType: 'profit_mult',
    effectValue: 3,
    unlockQuantity: 50,
  },
  {
    id: 703,
    businessId: 7,
    name: 'AI加速研发',
    description: 'AI辅助缩短研发周期，速度+25%',
    icon: '🧬',
    cost: 149299200000,
    effectType: 'cycle_reduce',
    effectValue: 0.25,
    unlockQuantity: 100,
  },

  // === 产线8: 品牌联名事业部 ===
  {
    id: 801,
    businessId: 8,
    name: '限量发售',
    description: '饥饿营销策略，利润翻倍',
    icon: '🏷️',
    cost: 17915904000,
    effectType: 'profit_mult',
    effectValue: 2,
    unlockQuantity: 25,
  },
  {
    id: 802,
    businessId: 8,
    name: '跨界联名',
    description: '与奢侈品品牌联名，利润×3',
    icon: '👑',
    cost: 179159040000,
    effectType: 'profit_mult',
    effectValue: 3,
    unlockQuantity: 50,
  },
  {
    id: 803,
    businessId: 8,
    name: '快闪店模式',
    description: '快闪店极速周转，速度+25%',
    icon: '✨',
    cost: 1791590400000,
    effectType: 'cycle_reduce',
    effectValue: 0.25,
    unlockQuantity: 100,
  },

  // === 产线9: 海外分销中心 ===
  {
    id: 901,
    businessId: 9,
    name: '自贸区优势',
    description: '利用自贸区政策，利润翻倍',
    icon: '🌍',
    cost: 214990848000,
    effectType: 'profit_mult',
    effectValue: 2,
    unlockQuantity: 25,
  },
  {
    id: 902,
    businessId: 9,
    name: '全球渠道',
    description: '覆盖100个国家渠道，利润×3',
    icon: '🌐',
    cost: 2149908480000,
    effectType: 'profit_mult',
    effectValue: 3,
    unlockQuantity: 50,
  },
  {
    id: 903,
    businessId: 9,
    name: '海外仓网络',
    description: '全球海外仓极速配送，速度+25%',
    icon: '🚀',
    cost: 21499084800000,
    effectType: 'cycle_reduce',
    effectValue: 0.25,
    unlockQuantity: 100,
  },

  // === 产线10: 全球屏保集团 ===
  {
    id: 1001,
    businessId: 10,
    name: '行业标准',
    description: '制定行业质量标准，利润翻倍',
    icon: '📜',
    cost: 2579890176000,
    effectType: 'profit_mult',
    effectValue: 2,
    unlockQuantity: 25,
  },
  {
    id: 1002,
    businessId: 10,
    name: '全球垄断',
    description: '全球市场份额80%，利润×3',
    icon: '🏆',
    cost: 25798901760000,
    effectType: 'profit_mult',
    effectValue: 3,
    unlockQuantity: 50,
  },
  {
    id: 1003,
    businessId: 10,
    name: '量子传送',
    description: '量子级供应链，速度+25%',
    icon: '⚛️',
    cost: 257989017600000,
    effectType: 'cycle_reduce',
    effectValue: 0.25,
    unlockQuantity: 100,
  },
];
