// ============================================================
// 产线配置 (BusinessDef) — 10档贴膜产业
// 数值对标 Adventure Capitalist 节奏，40~60分钟可首次转生
// ============================================================
import { BusinessDef } from '../types';

export const BUSINESSES: BusinessDef[] = [
  {
    id: 1,
    name: '路边钢化膜摊',
    order: 1,
    icon: 'stall',
    baseCost: 4,
    costCurve: 'exponential',
    costMultiplier: 1.07,
    baseCycleSec: 0.6,
    baseRevenue: 1,
    milestones: [
      { at: 10, multiplier: 2, label: '回头客越来越多！' },
      { at: 25, multiplier: 2, label: '整条街都在排队！' },
      { at: 50, multiplier: 2, label: '手机贴膜一条龙！' },
      { at: 100, multiplier: 2, label: '全城贴膜王者！' },
      { at: 200, multiplier: 2, label: '数码城传奇！' },
      { at: 500, multiplier: 2, label: '膜界泰斗！' },
      { at: 1000, multiplier: 2, label: '贴膜之神降临！' },
    ],
    managerId: 1,
    unlockRule: { type: 'tutorial_complete', value: 0 },
    flavorText: '手艺活起家，一刀下去满屏好评',
    autoBuyUnlockCost: 5,
  },
  {
    id: 2,
    name: '校园快贴车',
    order: 2,
    icon: '🚐',
    baseCost: 60,
    costCurve: 'exponential',
    costMultiplier: 1.15,
    baseCycleSec: 3,
    baseRevenue: 60,
    milestones: [
      { at: 10, multiplier: 2, label: '校门口排队到操场！' },
      { at: 25, multiplier: 2, label: '每个宿舍都贴上了！' },
      { at: 50, multiplier: 2, label: '全校手机膜都你包了！' },
      { at: 100, multiplier: 2, label: '隔壁学校都来找你！' },
      { at: 200, multiplier: 2, label: '大学城贴膜霸主！' },
      { at: 500, multiplier: 2, label: '校园创业第一人！' },
      { at: 1000, multiplier: 2, label: '教育界膜王！' },
    ],
    managerId: 2,
    unlockRule: { type: 'total_earned', value: 50 },
    flavorText: '走街串巷，课间10分钟能贴30台',
    autoBuyUnlockCost: 10,
  },
  {
    id: 3,
    name: '商场贴膜亭',
    order: 3,
    icon: '🏬',
    baseCost: 720,
    costCurve: 'exponential',
    costMultiplier: 1.14,
    baseCycleSec: 6,
    baseRevenue: 540,
    milestones: [
      { at: 10, multiplier: 2, label: '专柜位置全满了！' },
      { at: 25, multiplier: 2, label: '商场经理亲自来谈合作！' },
      { at: 50, multiplier: 2, label: '整层楼都是你的膜！' },
      { at: 100, multiplier: 2, label: '万达点名入驻！' },
      { at: 200, multiplier: 2, label: '全国商场疯抢！' },
      { at: 500, multiplier: 2, label: '商业地产新贵！' },
      { at: 1000, multiplier: 2, label: '膜业地产王！' },
    ],
    managerId: 3,
    unlockRule: { type: 'total_earned', value: 5000 },
    flavorText: '黄金位置日均进账，比卖手机还赚',
    autoBuyUnlockCost: 20,
  },
  {
    id: 4,
    name: '连锁门店',
    order: 4,
    icon: '🏪',
    baseCost: 8640,
    costCurve: 'exponential',
    costMultiplier: 1.13,
    baseCycleSec: 12,
    baseRevenue: 4320,
    milestones: [
      { at: 10, multiplier: 2, label: '十城百店计划完成！' },
      { at: 25, multiplier: 2, label: '加盟商挤破头！' },
      { at: 50, multiplier: 2, label: '每个城市核心商圈都有你！' },
      { at: 100, multiplier: 2, label: '上市公司请你去做顾问！' },
      { at: 200, multiplier: 2, label: '资本市场闻风而动！' },
      { at: 500, multiplier: 2, label: '连锁帝国正式建立！' },
      { at: 1000, multiplier: 2, label: '零售膜业教父！' },
    ],
    managerId: 4,
    unlockRule: { type: 'total_earned', value: 50000 },
    flavorText: '从单店到百店，加盟费比利润还高',
    autoBuyUnlockCost: 40,
  },
  {
    id: 5,
    name: '直播电商间',
    order: 5,
    icon: '📱',
    baseCost: 103680,
    costCurve: 'exponential',
    costMultiplier: 1.12,
    baseCycleSec: 24,
    baseRevenue: 51840,
    milestones: [
      { at: 10, multiplier: 2, label: '直播间同时10万人在线！' },
      { at: 25, multiplier: 2, label: '全网热搜第一！' },
      { at: 50, multiplier: 2, label: '带货榜永远的第一！' },
      { at: 100, multiplier: 2, label: '粉丝突破一亿！' },
      { at: 200, multiplier: 2, label: '直播膜界的天花板！' },
      { at: 500, multiplier: 2, label: '电商膜皇！' },
      { at: 1000, multiplier: 2, label: '直播界的传说！' },
    ],
    managerId: 5,
    unlockRule: { type: 'total_earned', value: 500000 },
    flavorText: '321上链接！1秒抢光10万张膜',
    autoBuyUnlockCost: 80,
  },
  {
    id: 6,
    name: 'OEM代工厂',
    order: 6,
    icon: '🏭',
    baseCost: 1244160,
    costCurve: 'exponential',
    costMultiplier: 1.11,
    baseCycleSec: 48,
    baseRevenue: 622080,
    milestones: [
      { at: 10, multiplier: 2, label: '产能翻十倍！' },
      { at: 25, multiplier: 2, label: '富士康都羡慕你的产线！' },
      { at: 50, multiplier: 2, label: '全球手机品牌排队下单！' },
      { at: 100, multiplier: 2, label: '工业4.0智能制造标杆！' },
      { at: 200, multiplier: 2, label: '世界工厂膜业分厂！' },
      { at: 500, multiplier: 2, label: '膜业制造之神！' },
      { at: 1000, multiplier: 2, label: '全球膜业供应链之王！' },
    ],
    managerId: 6,
    unlockRule: { type: 'total_earned', value: 5000000 },
    flavorText: '给大牌代工，一张膜成本2毛卖20',
    autoBuyUnlockCost: 160,
  },
  {
    id: 7,
    name: '纳米膜研发中心',
    order: 7,
    icon: '🔬',
    baseCost: 14929920,
    costCurve: 'exponential',
    costMultiplier: 1.10,
    baseCycleSec: 96,
    baseRevenue: 7464960,
    milestones: [
      { at: 10, multiplier: 2, label: '10项发明专利到手！' },
      { at: 25, multiplier: 2, label: 'nature杂志发论文！' },
      { at: 50, multiplier: 2, label: '诺贝尔膜学奖预定！' },
      { at: 100, multiplier: 2, label: '科技界膜学第一人！' },
      { at: 200, multiplier: 2, label: '未来科技膜业霸主！' },
      { at: 500, multiplier: 2, label: '科技膜帝！' },
      { at: 1000, multiplier: 2, label: '改变世界的膜！' },
    ],
    managerId: 7,
    unlockRule: { type: 'total_earned', value: 50000000 },
    flavorText: '自研纳米涂层技术，一张膜售价500起步',
    autoBuyUnlockCost: 320,
  },
  {
    id: 8,
    name: '品牌联名事业部',
    order: 8,
    icon: '🤝',
    baseCost: 179159040,
    costCurve: 'exponential',
    costMultiplier: 1.09,
    baseCycleSec: 192,
    baseRevenue: 89579520,
    milestones: [
      { at: 10, multiplier: 2, label: 'LV联名款秒空！' },
      { at: 25, multiplier: 2, label: '爱马仕请你喝下午茶！' },
      { at: 50, multiplier: 2, label: '全球奢侈品牌抢着联名！' },
      { at: 100, multiplier: 2, label: '膜界联名之王！' },
      { at: 200, multiplier: 2, label: '品牌溢价天花板！' },
      { at: 500, multiplier: 2, label: '联名帝国缔造者！' },
      { at: 1000, multiplier: 2, label: '品牌膜业的传奇！' },
    ],
    managerId: 8,
    unlockRule: { type: 'total_earned', value: 500000000 },
    flavorText: '联名款贴膜比奢侈品还难抢',
    autoBuyUnlockCost: 500,
  },
  {
    id: 9,
    name: '海外分销中心',
    order: 9,
    icon: '🌍',
    baseCost: 2149908480,
    costCurve: 'exponential',
    costMultiplier: 1.08,
    baseCycleSec: 384,
    baseRevenue: 1074954240,
    milestones: [
      { at: 10, multiplier: 2, label: '覆盖50个国家！' },
      { at: 25, multiplier: 2, label: '全球门店破万家！' },
      { at: 50, multiplier: 2, label: '每个时区都有你的膜！' },
      { at: 100, multiplier: 2, label: '世界膜业版图完成！' },
      { at: 200, multiplier: 2, label: '地球已经装不下你了！' },
      { at: 500, multiplier: 2, label: '星际膜业先驱！' },
      { at: 1000, multiplier: 2, label: '宇宙膜业霸主！' },
    ],
    managerId: 9,
    unlockRule: { type: 'total_earned', value: 5000000000 },
    flavorText: '纽约时代广场大屏都是你的广告',
    autoBuyUnlockCost: 750,
  },
  {
    id: 10,
    name: '全球屏保集团',
    order: 10,
    icon: '👑',
    baseCost: 25798901760,
    costCurve: 'exponential',
    costMultiplier: 1.07,
    baseCycleSec: 768,
    baseRevenue: 12899450880,
    milestones: [
      { at: 10, multiplier: 2, label: '全球屏保市场份额80%！' },
      { at: 25, multiplier: 2, label: '联合国都来谈合作！' },
      { at: 50, multiplier: 2, label: '手机不贴你的膜不敢出厂！' },
      { at: 100, multiplier: 2, label: '全球膜业垄断完成！' },
      { at: 200, multiplier: 2, label: '膜帝登基！' },
      { at: 500, multiplier: 2, label: '屏保界的上帝！' },
      { at: 1000, multiplier: 2, label: '贴膜大亨·宇宙终章！' },
    ],
    managerId: 10,
    unlockRule: { type: 'prestige_count', value: 1 },
    flavorText: '全宇宙的手机屏幕都被你承包了',
    autoBuyUnlockCost: 1000,
  },
];
