// ============================================================
// 游戏事件配置 — 随机事件系统（对标 Adventure Capitalist 事件）
// 事件周期性触发，为所有产线提供临时增益
// ============================================================
import { GameEventDef } from '../types';

export const GAME_EVENTS: GameEventDef[] = [
  // === 利润类事件 ===
  {
    id: 1,
    name: '网红直播带货',
    description: '一位千万级网红免费帮你宣传，全产线利润翻倍！',
    icon: 'nav/business',
    durationSec: 60,
    boostType: 'profit_mult',
    boostValue: 2,
    weight: 30,
    cooldownSec: 180,
    minTotalEarned: 0,
    reward: { type: 'cash', value: 5000 },
  },
  {
    id: 2,
    name: '新品发布潮',
    description: '各大品牌争相发布新机，贴膜需求暴涨！全产线利润×3！',
    icon: 'boost/rocket',
    durationSec: 45,
    boostType: 'profit_mult',
    boostValue: 3,
    weight: 15,
    cooldownSec: 300,
    minTotalEarned: 100000,
    reward: { type: 'cash', value: 50000 },
  },
  {
    id: 3,
    name: '双十一狂欢',
    description: '全民网购日，贴膜订单如潮水般涌来！利润×5！',
    icon: 'boost/gift',
    durationSec: 30,
    boostType: 'profit_mult',
    boostValue: 5,
    weight: 8,
    cooldownSec: 600,
    minTotalEarned: 1000000,
    reward: { type: 'diamond', value: 1 },
  },
  {
    id: 4,
    name: '品牌背书',
    description: '行业权威媒体推荐你的贴膜品牌，利润×1.5',
    icon: 'nav/achievement',
    durationSec: 90,
    boostType: 'profit_mult',
    boostValue: 1.5,
    weight: 35,
    cooldownSec: 120,
    minTotalEarned: 0,
  },

  // === 速度类事件 ===
  {
    id: 5,
    name: '自动化设备升级',
    description: '全自动贴膜机器人到货，生产速度×2！',
    icon: 'nav/manager',
    durationSec: 60,
    boostType: 'speed_mult',
    boostValue: 2,
    weight: 25,
    cooldownSec: 180,
    minTotalEarned: 0,
    reward: { type: 'cash', value: 3000 },
  },
  {
    id: 6,
    name: '流水线改造',
    description: '工业设计师优化了流水线，生产速度×3！',
    icon: 'boost/lightning',
    durationSec: 45,
    boostType: 'speed_mult',
    boostValue: 3,
    weight: 12,
    cooldownSec: 300,
    minTotalEarned: 500000,
    reward: { type: 'cash', value: 30000 },
  },
  {
    id: 7,
    name: '时停贴膜术',
    description: '传说级技能发动！生产速度×5！',
    icon: 'boost/timer',
    durationSec: 20,
    boostType: 'speed_mult',
    boostValue: 5,
    weight: 5,
    cooldownSec: 600,
    minTotalEarned: 2000000,
    reward: { type: 'diamond', value: 1 },
  },

  // === 全能类事件（利润+速度同时加成） ===
  {
    id: 8,
    name: '金色星期五',
    description: '财神的祝福降临！利润和速度都翻倍！',
    icon: 'boost/lightning',
    durationSec: 40,
    boostType: 'all_mult',
    boostValue: 2,
    weight: 10,
    cooldownSec: 420,
    minTotalEarned: 100000,
    reward: { type: 'cash', value: 20000 },
  },
  {
    id: 9,
    name: '膜帝降临',
    description: '传说中膜帝的英灵显灵，一切×3！',
    icon: 'nav/achievement',
    durationSec: 25,
    boostType: 'all_mult',
    boostValue: 3,
    weight: 3,
    cooldownSec: 900,
    minTotalEarned: 10000000,
    reward: { type: 'diamond', value: 3 },
  },

  // === 成本类事件 ===
  {
    id: 10,
    name: '原料大降价',
    description: '原材料供应商清仓大甩卖，购买成本减半！',
    icon: 'boost/gift',
    durationSec: 90,
    boostType: 'cost_reduce',
    boostValue: 0.5,
    weight: 20,
    cooldownSec: 240,
    minTotalEarned: 0,
  },
  {
    id: 11,
    name: '政府补贴',
    description: '获得创业扶持补贴，购买成本再降75%！',
    icon: 'nav/achievement',
    durationSec: 60,
    boostType: 'cost_reduce',
    boostValue: 0.25,
    weight: 10,
    cooldownSec: 360,
    minTotalEarned: 200000,
    reward: { type: 'cash', value: 10000 },
  },
];
