// ============================================================
// 店长配置 (ManagerDef) — 每档产线1名自动化店长
// ============================================================
import { ManagerDef } from '../types';

export const MANAGERS: ManagerDef[] = [
  {
    id: 1,
    name: '王师傅',
    businessId: 1,
    effectType: 'auto_run',
    effectValue: 1,
    unlockCost: 1000,
    currency: 'cash',
    rarity: 'common',
    icon: '👨‍🔧',
    description: '干了20年贴膜的老手，闭着眼都能贴出完美无气泡的膜',
  },
  {
    id: 2,
    name: '小陈学长',
    businessId: 2,
    effectType: 'auto_run',
    effectValue: 1,
    unlockCost: 15000,
    currency: 'cash',
    rarity: 'common',
    icon: '🎓',
    description: '学生会主席，把贴膜车开到了每个校区，生意好到炸',
  },
  {
    id: 3,
    name: '张店长',
    businessId: 3,
    effectType: 'auto_run',
    effectValue: 1,
    unlockCost: 100000,
    currency: 'cash',
    rarity: 'common',
    icon: '👩‍💼',
    description: '前商场楼层经理，熟知每个档口的流量密码',
  },
  {
    id: 4,
    name: '刘总',
    businessId: 4,
    effectType: 'auto_run',
    effectValue: 1,
    unlockCost: 500000,
    currency: 'cash',
    rarity: 'rare',
    icon: '👔',
    description: '连锁加盟领域20年老兵，标准化手册写了300页',
  },
  {
    id: 5,
    name: '网红小李',
    businessId: 5,
    effectType: 'auto_run',
    effectValue: 1,
    unlockCost: 2000000,
    currency: 'cash',
    rarity: 'rare',
    icon: '🎬',
    description: '粉丝3000万的膜界顶流，一句"买它"能卖光一个仓库',
  },
  {
    id: 6,
    name: '赵厂长',
    businessId: 6,
    effectType: 'auto_run',
    effectValue: 1,
    unlockCost: 10000000,
    currency: 'cash',
    rarity: 'rare',
    icon: '🏭',
    description: '代工行业老炮，产能调度精准到秒，废品率不到0.01%',
  },
  {
    id: 7,
    name: '陈博士',
    businessId: 7,
    effectType: 'auto_run',
    effectValue: 1,
    unlockCost: 50000000,
    currency: 'cash',
    rarity: 'epic',
    icon: '🧪',
    description: '材料学博士，纳米涂层的专利持有人，学术圈膜界权威',
  },
  {
    id: 8,
    name: 'Lucy Wang',
    businessId: 8,
    effectType: 'auto_run',
    effectValue: 1,
    unlockCost: 500000000,
    currency: 'cash',
    rarity: 'epic',
    icon: '💎',
    description: '前LVMH大中华区VP，奢侈品牌联名就是她的朋友圈',
  },
  {
    id: 9,
    name: 'Jack Chen',
    businessId: 9,
    effectType: 'auto_run',
    effectValue: 1,
    unlockCost: 5000000000,
    currency: 'cash',
    rarity: 'legendary',
    icon: '✈️',
    description: '精通12国语言，全球供应链操盘手，一年飞30万公里',
  },
  {
    id: 10,
    name: '膜皇大帝',
    businessId: 10,
    effectType: 'auto_run',
    effectValue: 1,
    unlockCost: 50,
    currency: 'diamond',
    rarity: 'legendary',
    icon: '👑',
    description: '传说中的贴膜之神，据说他的膜能让手机自动升值',
  },
  // === 专家顾问（缩时/倍率） ===
  {
    id: 11,
    name: '效率大师·老周',
    businessId: 0, // 全局
    effectType: 'cycle_reduce',
    effectValue: 0.1, // 减少10%周期
    unlockCost: 5,
    currency: 'diamond',
    rarity: 'rare',
    icon: '⚡',
    description: '六西格玛黑带，专治各种生产效率低下',
  },
  {
    id: 12,
    name: '定价之神·钱姐',
    businessId: 0, // 全局
    effectType: 'profit_mult',
    effectValue: 0.15, // 增加15%利润
    unlockCost: 10,
    currency: 'diamond',
    rarity: 'epic',
    icon: '💰',
    description: '商学院教授转行，定价策略能让利润翻三倍',
  },
];
